name: Publish release on push to main

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current date as version
        run: echo "VERSION=$(date +'%y.%-m.%-d')" >> $GITHUB_ENV

      - name: Set up binaries directory
        run: mkdir -p binaries

      - name: Add Windows target
        run: |
          sudo apt update && sudo apt install -y mingw-w64
          rustup target add x86_64-pc-windows-gnu

      - name: Build binary for Linux
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
          mv target/x86_64-unknown-linux-gnu/release/laptop_guard binaries/fdf-${{ env.VERSION }}-linux

      - name: Build binary for Windows
        run: |
          cargo build --release --target x86_64-pc-windows-gnu
          mv target/x86_64-pc-windows-gnu/release/laptop_guard.exe binaries/fdf-${{ env.VERSION }}-windows.exe

      - name: Delete existing release if exists
        continue-on-error: true
        run: |
          gh release delete "${{ env.VERSION }}" --yes
          git push --delete origin "${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Github release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ env.VERSION }}"
          name: "${{ env.VERSION }}"
          draft: false
          prerelease: true
          files: binaries/*
          generate_release_notes: true
